Skip `test_write_correct_frame_rate` and `test_write_larger_than_frame_rate`
These two tests fail on CI with:

```
ValueError: Could not initialize SDL audio - b'Could not setup connection to PulseAudio'
```

They seem new failures and unrelated to #37, because they fail the same way even if we still bundle those binaries.